version: '3.5'

services:
  
  api:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./src/api:/usr/share/nginx
        - ./src/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
    depends_on:
      - php
  
  php:
    build:
      context: './src/api'
    volumes:
      - ./src/api:/usr/share/nginx
    command: bash -c "composer install ;php-fpm"

